POST http://localhost:8001/user/signup
Content-Type: application/json

{
  "email": "hi@hi.hi",
  "password": "password",
  "username": "mycoolusername"
}

###

POST http://localhost:8001/user/signin HTTP/2
Content-Type: application/json

{
  "email": "hi@hi.hi",
  "password": "password"
}

###

POST http://localhost:8001/user/request-reset-password HTTP/2
Content-Type: application/json

{
  "email": "hi@hi.hi"
}

###

POST http://localhost:8001/user/reset-password HTTP/2
Content-Type: application/json

{
  "token": "3827741286403972946",
  "new_password": "password1"
}